### ISSUE TITLE
云产品流转里面的脚本应该怎么写

### ISSUE THREAD

**Issue by Flanwale** [Dianne722/MAX30102-STM32-ESP8266-APP-OLED#1]
想问问阿里云的云产品流转，app和硬件都能连上，但数据不知道怎么传

**Comment by Dianne722** [comment]
你可以看看那个b站的 漫天飞羽 有教程哈 这个项目我最近没在写了



---原始邮件---
发件人: "Zhe ***@***.***&gt;
发送时间: 2024年5月25日(周六) 下午4:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Dianne722/MAX30102-STM32-ESP8266-APP-OLED] 云产品流转里面的脚本应该怎么写 (Issue #1)




 
想问问阿里云的云产品流转，app和硬件都能连上，但数据不知道怎么传

**Comment by Flanwale** [comment]
感谢感谢，已经会啦
